### ISSUE TITLE
Register aliases don't work as parameter in many instructions

### ISSUE THREAD

**Issue by Kulasko** [ForwardCom/bintools#3]
Maybe this is linked to registers that set the size?
I got this problem with the size register for "broad" and "set_len", I haven't tried more yet.

Register aliases are almost useless in this cases.

**Comment by AgnerF** [comment]
This works:
```
%rrr = r1
%nnn = r2
%vvv = v5
int32 vvv = [rrr, length = nnn]
```
Please provide a test case.

**Comment by Kulasko** [comment]
```
    % value = r2
    % size = r3
    // get the array length as vector
    int32 v0 = gp2vec(value)
    int32 v0 = broad(size, v0) // Aliases dont work here, why?
```

This works if I use r3 at the commented place, but doesn't if I use the alias.

**Comment by AgnerF** [comment]
File assem4.cpp fixed. Does it work now?

**Comment by Kulasko** [comment]
Please excuse the late reply.
It does work now in almost all cases I tested. The notable exception are the push and pop instructions.

```
% test_data = r0
% stack_pointer = r31

int64 push(stack_pointer, test_data) // does not work
int64 push(r31, test_data) // does not work
int64 push(stack_pointer, r0) // does not work
int64 push(r31, r0) // works
```

**Comment by AgnerF** [comment]
Fixed file assem5.cpp

**Comment by Kulasko** [comment]
The issue seems to be resolved. Thank you for your work.

**Comment by Kulasko** [comment]
The issue still persists in vector loop statements.

**Comment by AgnerF** [comment]
Fixed file assem5.cpp

**Comment by Kulasko** [comment]
The mock memory operand works now, but the mock iterating register still doesn't.

**Comment by AgnerF** [comment]
It works for me in your mandelbrot example.

**Comment by Kulasko** [comment]
My mandelbrot example works because I did not use register aliases in order to be able assemble it.
This works:
```
for (v0 in [r0 - r1]) {}
% pointer = r0
% index = r1
for (v0 in [pointer - index]) {}
```
This does not:
```
% value = v0
for (value in [pointer - index]) {}
```

**Comment by AgnerF** [comment]
fixed assem5.cpp

**Comment by Kulasko** [comment]
That fix doesn't seem working, the behavior hasn't changed for me. I have compiled the assembler from source with the file version from yesterday.

**Comment by AgnerF** [comment]
Fixed file assem5.cpp again

**Comment by Kulasko** [comment]
It now works as expected. Thank you for your work.
